default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rss_developments
  
test:
  <<: *default
  database: rss_test
  
production:
  <<: *default
  database: rss_production
  username: rss
  password: <%= ENV["NEW_DELIVERY_DATABASE_PASSWORD"] %>
